language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
    - python milestone2demo.py < demo_test.txt
after_success:
    - coveralls
